// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WowPaperTrader.Persistence;

#nullable disable

namespace WowPaperTrader.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915044647_AddCurrentPriceLevels")]
    partial class AddCurrentPriceLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ErrorStack")
                        .HasColumnType("text");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AuctionMarketType")
                        .HasColumnType("integer");

                    b.Property<long?>("ConnectedRealmId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .IsUnique()
                        .HasDatabaseName("UX_AuctionMarkets_Region_RegionalCommodities")
                        .HasFilter("\"AuctionMarketType\" = 1");

                    b.HasIndex("ConnectedRealmId", "Region")
                        .IsUnique()
                        .HasDatabaseName("UX_AuctionMarkets_Region_ConnectedRealmId")
                        .HasFilter("\"AuctionMarketType\" = 2");

                    b.ToTable("AuctionMarkets", t =>
                        {
                            t.HasCheckConstraint("CK_AuctionMarkets_AuctionMarketType_ConnectedRealmId", "(\n    (\"AuctionMarketType\" = 1 AND \"ConnectedRealmId\" IS NULL)\n    OR\n    (\"AuctionMarketType\" = 2 AND \"ConnectedRealmId\" IS NOT NULL)\n)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuctionMarketType = 1,
                            DisplayName = "US Commodities",
                            Region = "US"
                        });
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarketSnapshot", b =>
                {
                    b.Property<long>("AuctionMarketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApiEndPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionMarketId", "ObservedAtUtc");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("AuctionMarketSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.CurrentPriceLevel", b =>
                {
                    b.Property<long>("AuctionMarketId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("VariantKey")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("AuctionMarketSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("ListingCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("AuctionMarketId", "ItemId", "VariantKey", "UnitPrice");

                    b.HasIndex("AuctionMarketId", "ObservedAtUtc");

                    b.ToTable("CurrentPriceLevels");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.ItemMarketSnapshot", b =>
                {
                    b.Property<long>("AuctionMarketId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("VariantKey")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FilterApplied")
                        .HasColumnType("boolean");

                    b.Property<long>("FilteredListingCount")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FilteredMeanUnitPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("numeric(28,6)");

                    b.Property<long?>("FilteredMinimumUnitPrice")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("FilteredQuantityWeightedMeanUnitPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("numeric(28,6)");

                    b.Property<long>("FilteredTotalQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ListingCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LowerFenceUnitPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("numeric(28,6)");

                    b.Property<decimal>("MeanUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("MedianUnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("MinimumUnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("P10UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("P25UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("P75UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("P90UnitPrice")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuantityWeightedMeanUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("TotalQuantity")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UpperFenceUnitPrice")
                        .HasPrecision(28, 6)
                        .HasColumnType("numeric(28,6)");

                    b.HasKey("AuctionMarketId", "ItemId", "VariantKey", "ObservedAtUtc");

                    b.HasIndex("AuctionMarketId", "ObservedAtUtc");

                    b.ToTable("ItemMarketSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommodityAuctionSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityAuctionSnapshotId");

                    b.HasIndex("ItemId", "CommodityAuctionSnapshotId")
                        .HasDatabaseName("IX_CommodityAuctions_ItemId_CommodityAuctionSnapshotId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ItemId", "CommodityAuctionSnapshotId"), new[] { "UnitPrice", "Quantity" });

                    b.ToTable("CommodityAuctions");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiEndPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAtUtc")
                        .HasDatabaseName("IX_CommodityAuctionSnapshots_FetchedAtUtc");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("CommodityAuctionSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.UpdateItems.ItemMetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CraftingReagent")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("InventoryType")
                        .HasColumnType("text");

                    b.Property<string>("InventoryTypeName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemClassId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemClassName")
                        .HasColumnType("text");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ItemSubclassId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemSubclassName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastFetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfessionName")
                        .HasColumnType("text");

                    b.Property<int?>("ProfessionSkillLevel")
                        .HasColumnType("integer");

                    b.Property<long?>("PurchasePrice")
                        .HasColumnType("bigint");

                    b.Property<int?>("PurchaseQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("QualityName")
                        .HasColumnType("text");

                    b.Property<string>("QualityType")
                        .HasColumnType("text");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<long?>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("SkillDisplayString")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItemMetaData");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarketSnapshot", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarket", "AuctionMarket")
                        .WithMany("MarketSnapshots")
                        .HasForeignKey("AuctionMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", "IngestionRun")
                        .WithMany("MarketSnapshots")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionMarket");

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.CurrentPriceLevel", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarketSnapshot", "AuctionMarketSnapshot")
                        .WithMany("CurrentPriceLevels")
                        .HasForeignKey("AuctionMarketId", "ObservedAtUtc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionMarketSnapshot");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.ItemMarketSnapshot", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarketSnapshot", "AuctionMarketSnapshot")
                        .WithMany("ItemMarketSnapshots")
                        .HasForeignKey("AuctionMarketId", "ObservedAtUtc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionMarketSnapshot");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuction", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", "CommodityAuctionSnapshot")
                        .WithMany("CommodityAuctions")
                        .HasForeignKey("CommodityAuctionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommodityAuctionSnapshot");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", b =>
                {
                    b.Navigation("MarketSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarket", b =>
                {
                    b.Navigation("MarketSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.MarketAggregates.AuctionMarketSnapshot", b =>
                {
                    b.Navigation("CurrentPriceLevels");

                    b.Navigation("ItemMarketSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.Navigation("CommodityAuctions");
                });
#pragma warning restore 612, 618
        }
    }
}
