// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WowPaperTrader.Persistence;

#nullable disable

namespace WowPaperTrader.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260520113851_AddPriceHistoryReadIndexes")]
    partial class AddPriceHistoryReadIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommodityAuctionSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityAuctionSnapshotId");

                    b.HasIndex("ItemId", "CommodityAuctionSnapshotId")
                        .HasDatabaseName("IX_CommodityAuctions_ItemId_CommodityAuctionSnapshotId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ItemId", "CommodityAuctionSnapshotId"), new[] { "UnitPrice", "Quantity" });

                    b.ToTable("CommodityAuctions");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiEndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAtUtc")
                        .HasDatabaseName("IX_CommodityAuctionSnapshots_FetchedAtUtc");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("CommodityAuctionSnapshots");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.UpdateItems.ItemMetaData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CraftingReagent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("bit");

                    b.Property<int?>("ItemClassId")
                        .HasColumnType("int");

                    b.Property<string>("ItemClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ItemSubclassId")
                        .HasColumnType("int");

                    b.Property<string>("ItemSubclassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastFetchedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<string>("ProfessionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionSkillLevel")
                        .HasColumnType("int");

                    b.Property<long?>("PurchasePrice")
                        .HasColumnType("bigint");

                    b.Property<int?>("PurchaseQuantity")
                        .HasColumnType("int");

                    b.Property<string>("QualityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<long?>("SellPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("SkillDisplayString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemMetaData");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuction", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", "CommodityAuctionSnapshot")
                        .WithMany("CommodityAuctions")
                        .HasForeignKey("CommodityAuctionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommodityAuctionSnapshot");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.HasOne("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("WowPaperTrader.Application.Features.Write.AuctionHouseSnapshot.WowApiResult.CommodityAuctionSnapshot", b =>
                {
                    b.Navigation("CommodityAuctions");
                });
#pragma warning restore 612, 618
        }
    }
}
