// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace wow_paper_trader.Ingestor.Migrations
{
    [DbContext(typeof(IngestorDbContext))]
    [Migration("20260213055952_ChangeUnitPriceAndQuantityToBigint")]
    partial class ChangeUnitPriceAndQuantityToBigint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommodityAuction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommodityAuctionSnapshotId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeLeft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommodityAuctionSnapshotId");

                    b.ToTable("CommodityAuctions");
                });

            modelBuilder.Entity("CommodityAuctionSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiEndPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IngestionRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.ToTable("CommodityAuctionSnapshots");
                });

            modelBuilder.Entity("IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("CommodityAuction", b =>
                {
                    b.HasOne("CommodityAuctionSnapshot", "CommodityAuctionSnapshot")
                        .WithMany("CommodityAuctions")
                        .HasForeignKey("CommodityAuctionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommodityAuctionSnapshot");
                });

            modelBuilder.Entity("CommodityAuctionSnapshot", b =>
                {
                    b.HasOne("IngestionRun", "IngestionRun")
                        .WithMany()
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("CommodityAuctionSnapshot", b =>
                {
                    b.Navigation("CommodityAuctions");
                });
#pragma warning restore 612, 618
        }
    }
}
